import 'package:get/get.dart';

class Translator extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'HOME': 'HOME',
      'login': 'Login',
      'Sign up': 'Sign up',
      'username': 'Username',
      'password': 'Password',
      'enter_otp': 'Enter OTP',
      'verify_otp': 'Verify OTP',
      'login_successful': 'Logged in successfully!',
      'otp_invalid': 'Invalid OTP, please try again.',
      'error': 'Error',
      'enter_credentials': 'Please enter your credentials.',
      'invalid_otp': 'Invalid OTP format.',
      'My Cars': 'My Cars',
      'Favorites': 'Favorites',
      'Home': 'Home',
      'Settings': 'Settings',
      'Shop': 'Shop',
      'Map': 'Map',
      'Work': 'Work',
      'Travel': 'Travel',
      'Garage': 'Garage',
      'Contact': 'Contact',
      'Search Page': 'Search Page',
      'Notifications Page': 'Notifications Page',
      'Profile Page': 'Profile Page',
      'Page Not Found': 'Page Not Found',
      'ECU': 'ECU',
      'PARS': 'PARS',
    },
    'fa': {
      'HOME': 'خانه',
      'login': 'ورود',
      'Sign up': 'ثبت نام',
      'username': "نام کاربری",
      'password': 'رمز عبور',
      'enter_otp': 'کد ارسال شده را تایید کنید',
      'verify_otp': 'تایید کد بک بار مصرف',
      'login_successful': 'ورود موفقعیت امیز',
      'otp_invalid': "کد یکبار مصرف نامعتبر",
      'error': 'خظا',
      'enter_credentials': 'خظا اعتبار سنجی',
      'invalid_otp': "کد اعتبار سنجی نامعتر",
      'My Cars': 'ماشین‌های من',
      'Favorites': 'موارد دلخواه',
      'Home': 'خانه',
      'Settings': 'تنظیمات',
      'Shop': 'فروشگاه',
      'Map': 'نقشه',
      'Work': 'کار',
      'Travel': 'سفر',
      'Garage': 'گاراژ',
      'Contact': 'تماس',
      'Search Page': 'صفحه جستجو',
      'Notifications Page': 'صفحه اطلاعیه‌ها',
      'Profile Page': 'صفحه پروفایل',
      'Page Not Found': 'صفحه پیدا نشد',
      'ECU': 'ای سی یو',
      'PARS': 'پارس',
    },
  };
}
