name: treenode
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage:
  http:
  animate_do:
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/config.json

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/vazir.ttf
    - family: Sarbaz
      fonts:
        - asset: assets/fonts/sarbaz.ttf